name: github_test_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  dio: ^5.3.2
  provider: ^6.0.5
  shared_preferences: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf

  uses-material-design: true

